#!/bin/bash

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

# Upgrade meshcentral
cd /opt/meshcentral
scl enable rh-nodejs10 "npm install meshcentral"
sudo -u meshcentral scl enable rh-nodejs10 "timeout 15 node ./node_modules/meshcentral"

# Set meshcentral owns /opt/meshcentral after install for security
chown -R meshcentral:meshcentral /opt/meshcentral

# Set secure permissions
chmod -R 755 /opt/meshcentral/meshcentral-*
